### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by moonshanzhaoqin** [NetEase/Emmagee#100]
## The problem
http://url.cn/5ktGaYw 扫码安装的时候，下载成功，点击安装，提示应用未安装，无法完成安装
## Environment

* Emmagee version
* Device Information: **三星**, **普通模式**, **Android 6.0.1**.

## Link to Emmagee logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Emmagee logs, and link them here. 
Do _NOT_ paste your full Emmagee logs here, as it will make this issue very long and hard to read!

**Comment by andrewleo** [comment]
您下载的是别人修改后打的包，来源应该是这里：https://github.com/tobecrazy/Emmagee。这个apk没有签名文件，所以无法安装。
如果官方版本满足您的需求，可以在这里下载：https://github.com/NetEase/Emmagee/releases，或者您可以自行下载tobecrazy的代码编译打包使用

**Comment by moonshanzhaoqin** [comment]
结果文件CSV中，栈顶Activity名称：N/A  是什么意思啊 亲

在 2017年12月8日 下午3:54，Liu Xiao <notifications@github.com>写道：

**Comment by andrewleo** [comment]
您应该是在5.0及以上的机器用的Emmagee吧，5.0及以上由于系统的安全限制无法拿到topActivity了，所以限制是N/A。详细可见README：https://github.com/NetEase/Emmagee#android-50-and-above
