### ISSUE TITLE
想问下，您这个项目中，具体数据写入文件的方法在哪里呢，我怎么找不到呢

### ISSUE THREAD

**Issue by zhaolijunstar** [NetEase/Emmagee#101]
## The problem

Describe the issue you are experiencing, or features you want. 

## Environment

* Emmagee version
* Device Information: **Brand**, **Model**, **System**.

## Link to Emmagee logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Emmagee logs, and link them here. 
Do _NOT_ paste your full Emmagee logs here, as it will make this issue very long and hard to read!

**Comment by andrewleo** [comment]
在CpuInfo这个类里。用的EmmageeService.bw。这块很乱，一直没有重构 :(

**Comment by zhaolijunstar** [comment]
公共数据为什么写到那里面去啊？
