### ISSUE TITLE
I/O 负载测试

### ISSUE THREAD

**Issue by dezng** [NetEase/Emmagee#103]
应用某一版本的 anr 问题比较严重，新版本增加了较多的 log，怀疑和 i/o 有较大联系，但是不知道如何量化比较测试，想咨询下在 i/o 测试上，一般是怎么做的？

**Comment by andrewleo** [comment]
io方面的没有做过，一般客户端这方面的问题也比较少。
参考Linux，可以通过iostat来检测磁盘的io，或者vmstat也有简单的数据可以参考

**Comment by dezng** [comment]
`iostat` 我用的手机上没有这个命令，`vmstat` 中只有 `bi`/`bo`，pc 上可以 `vmstat -d` 查看详情，但是手机上只有简单的用法：
> usage: vmstat [-n] [DELAY [COUNT]]

**Comment by dezng** [comment]
读取 `/proc/PID/stat` 中的数据，根据`https://android.googlesource.com/kernel/x86_64/+/android-x86_64-cuttlefish-4.4-oreo-mr1/fs/proc/array.c#474`中的数据结构读到的缺页次数和 `dumpsys cpuinfo` 差距很大
```
# /proc/pid/stat
        min_flt: 189305
       cmin_flt: 0
        maj_flt: 2
       cmaj_flt: 0
```
```
# cpuinfo
faults: 8 minor
```

**Comment by andrewleo** [comment]
iostat需要安装的，装个busybox吧。
不一定要root，push到/data/local/tmp目录下，chmod成可执行文件就行
![image](https://user-images.githubusercontent.com/3241895/35558255-870fc37e-05e2-11e8-8a1d-1df1ccb04d88.png)
