### ISSUE TITLE
二次开发问题

### ISSUE THREAD

**Issue by zhaolijunstar** [NetEase/Emmagee#104]
## The problem

我在您的Emmagee上做了二次开发，启动app测出来的内存比用Emmagee高很多，然后同时打开Emmagee和二次开发的Emmagee，我二次开发的Emmagee显示的数据又和您的Emmagee一样了，我想问下这是什么问题，感觉我二次开发的Emmagee读取的文件和您的Emmagee读取的文件不同啊，但是我没修改读取文件的路径，求解答

## Environment

* Emmagee version
* Device Information: **Brand**, **Model**, **System**.

## Link to Emmagee logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Emmagee logs, and link them here. 
Do _NOT_ paste your full Emmagee logs here, as it will make this issue very long and hard to read!

**Comment by andrewleo** [comment]
额。这个问题有点诡异，读取文件一样的情况下，数据应该不会不同才对。
不过就您提供的这些信息，我也没法知道原因。如果方便可以把源码提供出来，大家一定看下是否哪里有不同。

**Comment by zhaolijunstar** [comment]
2、我用as3.1自带的内存测试工具测试我们的app，内存大概稳定在250M到300M,但是一打开您的Emmage，内存就下降到170到220，（您的Emmage和as自带的内存测试工具都下降了），这是怎么回事呀。
2、还有一个问题，您这个开源的代码，里面的文字都是英文的，但我下载的最新apk是中文的，想问下，这个源码和apk能对上吗？
3、这是我二次开发您的Emmagee的地址：https://github.com/zhaolijunstar/performance

**Comment by zhaolijunstar** [comment]
方便加个qq或者微信吗，我最近要在您的Emmagee上做二次开发，有很多问题想请教下

**Comment by andrewleo** [comment]
1、emmagee读取的内存是pss，这个pss是包含实际的物理内存+比例分配共享库占用的内存，所以在额外启动了一个app后，共享库平分的内存就少了，所以数值也会降低，这可能是原因，而且您还需要确认下as获取的内存是哪个数值，pss,uss,vss,rss?
2、文字是英文，这个默认是英文的，不过也要看你手机设置的语言。中文配置在这里：res/values-zh-rCN/strings.xml

**Comment by zhaolijunstar** [comment]
<img width="1021" alt="7091c626f108b211a46b779262b4b00b" src="https://user-images.githubusercontent.com/27919193/35616492-5a787df0-06b0-11e8-858e-27eff8cc6d8d.png">
1、as没有包含私有内存呀，打开您的Emmage后，您的Emmage和as自带内存监测工具的数值为什么会同时下降？

**Comment by zhaolijunstar** [comment]
这是as 的内存监测工具的官方文档：https://developer.android.com/studio/profile/memory-profiler.html

**Comment by andrewleo** [comment]
Emmagee下降是可以解释的，因为Emmagee取得是PSS，多起一个Emmagee进程则共享进程就被再次平均，所以PSS会下降是没问题。
至于as，如果真如官网所说只是应用自身，那我想不通为什么启动一个第三方的进程（Emmagee），怎么会对原本应用内存有影响，除非说你手机内存不足部分被回收给了Emmagee？

**Comment by zhaolijunstar** [comment]
不是Emmagee的内存下降了，是Emmagee监控的我们的app的内存下降了

**Comment by andrewleo** [comment]
恩，我说错了，就是Emmagee监控的你们的App下降是可解释的。
```
多起一个Emmagee进程则共享进程就被再次平均，所以PSS会下降是没问题。
```
比如本来共享内存是100M，只有你们自己的App在使用，那PSS = 实际物理内存+ 100M
但如果Emmagee启动了，使用了共享库，那PSS统计到的数据 = 实际物理内存 + 100M/2

**Comment by CxBingo** [comment]
你好，为什么不联网的状态下就采集不到电流数据，这个应用是必须在联网状态下使用吗？

**Comment by andrewleo** [comment]
所有数据的获取都不需要联网.
电流数据由于不同手机不一样，需要适配。也可能是没有适配的原因而非联网关系

**Comment by CxBingo** [comment]
那请问市面上哪些手机适配了获取电流数据呢，

**Comment by andrewleo** [comment]
https://github.com/NetEase/Emmagee/blob/master/src/com/netease/qa/emmagee/utils/CurrentInfo.java 可以看下代码哈。
由于电流的获取并不准只具备参考的意义，而且适配比较麻烦。所以当前并没有适配很多手机

**Comment by andrewleo** [comment]
不过目前已知的大部分电流的读取都来自于代码中那些文件，所以修改后应该可以支持更多

**Comment by CxBingo** [comment]
好的，非常感谢

**Comment by CxBingo** [comment]
下载源码以后使用ant -f emmagee.xml 出现build faild 
win_update_project:
     [exec] **************************************************************************
     [exec] The "android" command is deprecated.
     [exec] For manual SDK, AVD, and project management, please use Android Studio.
     [exec] For command-line tools, use tools\bin\sdkmanager.bat
     [exec] and tools\bin\avdmanager.bat
     [exec] **************************************************************************
     [exec]
     [exec] Invalid or unsupported command "update project -n Emmagee -p ."
     [exec]
     [exec] Supported commands are:
     [exec] android list target
     [exec] android list avd
     [exec] android list device
     [exec] android create avd
     [exec] android move avd
     [exec] android delete avd
     [exec] android list sdk
     [exec] android update sdk

请问是什么原因？
