### ISSUE TITLE
关于抓取的cpu、memory准确性问题

### ISSUE THREAD

**Issue by vigossjjj** [NetEase/Emmagee#18]
Hi，there

最近研究了一下android性能测试，关于数据的抓取，memory、内存，网上有很多方法，我大概看了一下 有procrank、dumsys meminfo、dumpsys cpuinfo、top等。

今天看了一emmagee的内存抓取，是通过ActivityManager的getProcessMemoryInfo，按pid抓取，cpu是读取/proc/processPid/stat 下的信息。我通过以上几种方法还有QQ的GT抓取了下相同场景的内存，cpu消耗，差别有点大。。。

希望可以解释一下emmagee所选取的捕获内存，cpu方法的理由？

THX~

**Comment by CYsuncheng** [comment]
请问，dumpsys cpuinfo 和 top 查看的cpu 会有很大的差别，只是间隔问题么？
