### ISSUE TITLE
关于测试结束后，发送邮箱的问题

### ISSUE THREAD

**Issue by mrljdx** [NetEase/Emmagee#22]
在点击停止测试后，会将测试文件以邮件方式发送到一个未知邮箱。这个邮箱的地址是？

**Comment by 815901456** [comment]
请问这个邮件配置是怎么配置的？

**Comment by andrewleo** [comment]
进入到设置邮件配置里面，除了账号密码还需要smtp
163的话是smtp.163.com，其他的也可以网上查找到，可以自行搜索下
