### ISSUE TITLE
Emmagee配合脚本做自动化问题。

### ISSUE THREAD

**Issue by seasoncool** [NetEase/Emmagee#27]
感谢 Emmagee团队做出了这么好的一款APP产品。

我们一直用它做手机app的功耗 流量 CPU 等等的测试，效果很好。

最近公司要求，我们需要在版本迭代后自动化，这里需要把Emmagee的测试结果集成进来，这样一来就有了几个问题，想请问下你们，谢谢。

1，安卓的自动化 不管用那种工具，都必须用 数据线连接 电脑来传输代码，经测试我们发现手机连接电脑时候Emmagee的电流，有时候是是正数有时候是负数，导致计算出来的功耗和手动上有很大的误差，这块想请问下你们怎么规避，我们尝试过关闭手机充电只留数据传输功能，很可惜没有一种方式成功。

2，我们用Appium自动测试程序的时候，在Emmagee的报告中，内存 和 CPU 这些地方会有 0 的 值，很是头疼，也不知道是哪里出了原因。
![image](https://cloud.githubusercontent.com/assets/6467295/4217490/424446ea-38e8-11e4-9e17-4e10b0d6fa3c.png)

谢谢Emmagee团队，有任何的思路都可以分享下。

**Comment by smallerdawn** [comment]
不过可以通过包名这个应用的唯一识别，监控时将当前正在运行的所有App的包名获取到，如果包含要监听的App，获取到相应的PID即可，这个方案应该是可行的。
这个方案需要我们写自动化的时候，修改emmagee的代码来实现监听吗？还是说emmagee本身就有这个功能的？

**Comment by andrewleo** [comment]
@smallerdawn 
Emmagee现在已经提供了根据包名而不是pid来判断进程是否已经不存在了。有个选项：“应用退出后停止监听”，勾选上后就可以继续监听，当app重新启动后仍然可以继续统计

**Comment by lilianyu** [comment]
和Appium配合做自动化性能统计，勾上选项“应用退出后停止监听”，得到的应用占用内存和cpu仍然为0。看起来和@andrewleo 描述的逻辑不一致。我用的方法有问题吗？

**Comment by andrewleo** [comment]
首先感谢反馈哈~
有以下三个问题需要和您确认下：
（1）您是否使用的最新版本：当前是2.4：https://github.com/NetEase/Emmagee/releases
（2）您配合Appium进行自动化的时候，是否是通过Appium启动的被测应用，而非通过Emmagee启动？

> Emmagee是通过启动被测应用后，得到pid继而获取应用的性能数据；目前并不支持监听指定PID，只有通过Emmagee启动的App才会监控。

所以如果您是这样操作的，那Emmagee就获取不到任何性能，因为它没有拿到pid
（3）如果以上两点都没问题，是否是Appium自动化时杀死了被测应用？因为一旦进程被杀死后重新启动，pid必然会变化，也就会导致使用原来的pid无法获取性能

**Comment by ancining** [comment]
@seasoncool 可以请教下你是如何通过无线连接的方式，往安卓端发送自动化的代码的

**Comment by andrewleo** [comment]
无需root，如下两个命令就可以哈。
* adb tcpip port
* adb connect ip:port

**Comment by ancining** [comment]
@andrewleo 睡个午觉就有回复，而且是来自你的回复，非常感谢，亲测可用，就连uiautomatorviewer都可以这样查看APP控件了，哈哈！只是Emmagee在我三星手机和联想手机里使用时流量都是无法正常使用，一个一直显示0，一个一直显示N/A，也许是机型没覆盖到吧，再次感谢！

**Comment by andrewleo** [comment]
用的是2.5.1版本吗？如果是的话，可以把如下信息贴出来，我定位下原因 :)
```
 Emmagee version
 Device Information: **Brand**, **Model**, **System**.
```

**Comment by ancining** [comment]
@andrewleo 抱歉，之前用的是2.4的，但是后来用了2.5的还是一样
[](![image](https://user-images.githubusercontent.com/26423615/30531984-514c2510-9c84-11e7-95e7-0a6fdb8551c2.png)，)日志由于太长，发到你的邮箱里了，谢谢
