### ISSUE TITLE
emmagee在退出客户端后会自动停止，建议不自动停止，只允许手动停止

### ISSUE THREAD

**Issue by renningning** [NetEase/Emmagee#37]
使用场景：使用MTC录制/回放时，开启emmagee监控客户端性能。

使用百度MTC录制用例后回放，若一条录制太长，回放时容易出错。新录制一条则会退出客户端。但退出客户端后emmagee就自动停止了。

希望退出客户端时emmagee不自动停止，再需要停止时再手动停止。

**Comment by andrewleo** [comment]
首先感谢反馈！
这种使用场景下由人工来停止监控确实会更方便，一份报告也更易于查看以及汇总；考虑将自动停止做成可选项，这样能适用于不同场景。
下个版本会添加改功能，请持续关注Emmagee~

**Comment by andrewleo** [comment]
2.3版本已添加该功能选项。请在此：https://github.com/NetEase/Emmagee/releases 下载使用
