### ISSUE TITLE
Emmagee 2.2在长虹 N1上面运行时，监控不到流量数据——导出的csv文件中，流量数据为N/A

### ISSUE THREAD

**Issue by jingpeng1982** [NetEase/Emmagee#39]
你好！

我在长虹N1上运行Emmagee 2.2监控我的APP时，发现监控不到流量数据——在导出的CSV文件一级悬浮窗中，流量数据为N/A。
请问在流量监控方面，有没有什么特殊的要求？
谢谢！

**Comment by andrewleo** [comment]
流量监控并没有什么特殊的设置，也不需要root权限。
监控是通过读取/proc/uid_stat/UID/下的文件获取，代码如下：
```
String rcvPath = "/proc/uid_stat/" + uid + "/tcp_rcv";
String sndPath = "/proc/uid_stat/" + uid + "/tcp_snd";
rcvTraffic = Long.parseLong(rafRcv.readLine());
sndTraffic = Long.parseLong(rafSnd.readLine());
```
这个路径下的文件第三方app是有权限读取的。如果流量为NA，请确认下
（1）该文件夹下是否存在tcp_rcv和tcp_snd这个文件
（2）如果存在可以cat下看看里面的数值。当前通过Long.parseLong转换，有可能你手机流量数据不是这个格式
