### ISSUE TITLE
Emmagee 2.3运行在Android5.0系统上，不在充电的情况下，检测不到电量数据

### ISSUE THREAD

**Issue by beiying** [NetEase/Emmagee#42]
hi，
   我在Android5.0系统上运行Emmagee 2.3，在充电情况（插在电脑上或插座上）下，可以检测到电量数据，不充电情况下，检测不到电量数据，这是什么原因？

**Comment by andrewleo** [comment]
首先感谢反馈！
你意思是无法获取设备的当前电量还是当前的电流值？
