### ISSUE TITLE
流量统计，是否有bug?

### ISSUE THREAD

**Issue by hong10** [NetEase/Emmagee#44]
traffic += (lastestTraffic - preTraffic + 1023) / 1024;
为什么要+1023；
这样统计出来的流量，在cvs表中的流量数据，呈有规律的递增趋势，这样的数据是不准确的

**Comment by andrewleo** [comment]
Emmagee流量最小单位是KB，这里的计算是将之<b>转化为KB后取整</b>。

当（lastestTraffic - preTraffic）%1024所得余数在1-1024间，均以（lastestTraffic - preTraffic）/1024+1KB作为最终的流量值，确实会较实际统计出来的流量值高出最多1KB

不过对你提到的的 <b>呈有规律的递增趋势</b> 不是很明白；
最终统计的流量也只会最多高出1KB，而不是每次统计高出1KB，导致误差越来越大

**Comment by hong10** [comment]
下面是我使用这个软件得到一列数据，我设置的是每5秒取值一次，发现后面的数据基本都是每次都会+1；
还有，询问一下，这一列累加，是否就是该应用在这段时间使用的总流量呢？

Net Traffic(KB)
40
47
76
78
86
89
89
90
91
92
93
95
95
95
96
96
97
98
99
100
101
101
103
104
104
105
105
105
106
106
106
107
107
107
109
111
112
113
113
114
115
116
117
117
118
121
128
129
130
130
130
132
133
133
134
134
135
137
137
138
139
139
140
140
140
141
143
144
146
146
146
147
147
147
148
148
149
156
158
160
162
162
164
165
165
166
166
166
167
167
167
169
170
170
171
171
173
181
181
182
183
183
187
189
189
190
190
190
192
192
193
195
202
203
207
209
210
211
213
214
215

**Comment by andrewleo** [comment]
你理解错了哈。
这个流量数值是从启动app开始到当前时刻的流量值，是整体的流量值，而这一列的最后一个值是该应用在这段时间使用的总流量。
代码中有如下一段：
```
traffic += (lastestTraffic - preTraffic + 1023) / 1024;
```

**Comment by hong10** [comment]
你好，可否留个email地址，沟通一下；
我看代码，开始理解是这一列的最后一个值是该应用在这段时间使用的总流量；
但是测试一款打电话的软件，保持通话10min，但是文件中的这一列的最后一个值只有200KB左右，这个现象让我很不解，可以解释一下吗？通话应该是比较费流量的，不会只有200KB吧；

**Comment by andrewleo** [comment]
邮箱地址可以在 <b>AUTHORS</b> 文件中找到哈：hz_liuxiao#corp.netease.com
如果通话中一直在走流量这个数值是太小了，具体问题请邮箱联系我们哈~

**Comment by fukuale** [comment]
我也想问一下这个问题

**Comment by fukuale** [comment]
同样是视频通话的软件，测试20几分钟，流量显示只有400KB，而手机系统自带的流量显示每秒都要消耗200多KB
