### ISSUE TITLE
流量统计有问题吗

### ISSUE THREAD

**Issue by jasonross** [NetEase/Emmagee#46]
TrafficInfo.java中，rcvTraffic = TrafficStats.getUidRxBytes(Integer.parseInt(uid));又去调用rcvTraffic = Long.parseLong(rafRcv.readLine())，那前面调用是不是没意义。

**Comment by andrewleo** [comment]
这个是我们的疏忽，上个版本修改为用API获取流量后，之前的代码忘记删除了。
使用官方API即可：getUidRxBytes
