### ISSUE TITLE
为什么电量和流量一直是N/A

### ISSUE THREAD

**Issue by cryingDream94** [NetEase/Emmagee#48]
![screenshot_2015-09-09-17-34-55](https://cloud.githubusercontent.com/assets/12590998/9758494/8ed7ff6a-5719-11e5-9899-2862e4ebbe3c.png)

**Comment by andrewleo** [comment]
感谢反馈。首先确认下你是否使用的是最新的[2.3版本](https://github.com/NetEase/Emmagee/releases/download/V2.3/Emmagee-2.3.apk).

1、电流的读取是不同机型获取的方式不同，无法做到适配所有设备。目前支持的机型有限，可能出现获取不到的情况，麻烦你把设备的详细型号列出来，我们看下是否可以支持
2、流量这个比较奇怪，你看下是否所有App都获取不到，还是只有你当前这个应用无法获取？

**Comment by cryingDream94** [comment]
之前确实不是最新版本，使用了2.3版本还是电量和流量获取不到。
1、手机型号：HTCD610t
2、确实是安装所有的App流量都获取不到

**Comment by andrewleo** [comment]
能导一份Emmagee监控期间的logcat日志上传上来吗？

**Comment by cryingDream94** [comment]
Package Name,me.ele
App Name,饿了么
App PID,22535
Device Memory Size(MB),828.11MB
Device CPU Type, ARMv7 Processor rev 3 (v7l)
Android Version,4.4.2
Device Brand/Model,HTC D610t
UID,10241
Timestamp,Top Activity Name,App Used Memory PSS(MB),App Used Memory(%),System Available Memory(MB),App Used CPU(%),Total Used CPU(%),cpu0 Total Usage(%),cpu1 Total Usage(%),cpu2 Total Usage(%),cpu3 Total Usage(%),Net Traffic(KB),Battery(%),Current(mA),Temperature(C),Voltage(V)
2015-09-22 17:27:12,ComponentInfo{com.netease.qa.emmagee/com.netease.qa.emmagee.activity.MainPageActivity},36.66,4.43,256.67,0,0,0.00,0.00,0.00,0.00,N/A,42,N/A,32.3,3.868
Note: for unsupported devices refer to: https://github.com/NetEase/Emmagee/wiki/Some-devices-are-not-supported
Current: negative for discharging while positive for charging
Start time: empty means either the app has been started or failed to fetch start time
N/A: not supported or data exception
