### ISSUE TITLE
目前有两个机型是5.0以上的系统，但是监听的所有Activity都是emmagee的，无法监听对应应用。

### ISSUE THREAD

**Issue by smallerdawn** [NetEase/Emmagee#49]
GT-I9508  5.0.1
HTC D816v 5.0.2
上面两个系统，监听到的Activity都是com.netease.qa.emmagee.activity.MainPageActivity
无法兼容我需要的应用的内存cpu数据等，想请求下什么原因呢？（操作红米1 4.2.2系统的是可以获取app的信息的）

**Comment by andrewleo** [comment]
原因是在android 5.0.1版本以上，google出于安全性考虑，不允许第三方应用获取当前运行的进程了，而为了保持向下兼容，这个方法会返回第三方应用的进程信息，官方对getRunningTasks的注释如下：

```
public List<ActivityManager.RunningTaskInfo> getRunningTasks (int maxNum)

Added in API level 1
This method was deprecated in API level 21.
As of LOLLIPOP, this method is no longer available to third party applications: the introduction of document-centric recents means it can leak person information to the caller. 
For backwards compatibility, it will still retu rn a small subset of its data: 
at least the caller's own tasks, and possibly some other tasks such as home that are known to not be sensitive.
```

官方说明：http://developer.android.com/intl/zh-cn/reference/android/app/ActivityManager.html#getRunningTasks(int)

我们会尝试是否可以找到其他方式获取，不过并不乐观。因为google正在逐渐废除之前的一些不太安全的方法，不止是getRunningTasks
