### ISSUE TITLE
能兼容到现在android最新的版本 6.0 不？

### ISSUE THREAD

**Issue by baimingyong** [NetEase/Emmagee#51]
能兼容到现在android最新的版本 6.0 不？
谢谢

**Comment by andrewleo** [comment]
由于设备有限，还没有在6.0的机器上测试过。
你那边使用Emmagee在6.0系统的设备上出现什么异常吗？

**Comment by andrewleo** [comment]
当前2.4版本已经可以支持6.0的系统了，你可以再确认下是否还有问题
