### ISSUE TITLE
使用有什么要求？

### ISSUE THREAD

**Issue by dezng** [NetEase/Emmagee#52]
是否需要root权限？设置里面提示统计heap数据需要root，我的理解就是其他但是我在使用时，部分信息无法正确获取。
使用Nexus 5，android 6.0.1时无法获取应用占用的内存和CPU信息，流量显示N/A，电流为负值。
使用Meizu pro 5，无法获取应用占用的内存和CPU信息，流量和电流显示N/A

**Comment by andrewleo** [comment]
首先确认下您是否用的最新apk：https://github.com/NetEase/Emmagee/releases/tag/V2.4 这里下载。
1、是否需要root权限？
目前heap值得统计是需要root的，其他数据比如cpu，内存等都不需要root
2、无法获取内存，cpu等问题
nexus，pro5 这两款手机都是6.0以上的版本吗？google慢慢开始限制第三方应用的权限了，目前6.0以上的机器还未测试，我们尽快验证，看下是权限问题还是Emmagee自身的Bug

**Comment by dezng** [comment]
好的，使用最新版测试结果：
pro5 还存在电流N/A
Nexus 5 电流显示偶现N/A
mx5 全部显示正常
其中mx 5已root，获取root权限后帧率显示正常

**Comment by andrewleo** [comment]
nexus，pro5 这两款手机都是6.0以上的版本吗？ 除了电流出现N/A以外，其他数值比如内存，CPU都可以获取的吗？

**Comment by dezng** [comment]
nexus 5是Android 6.0，pro 5是android 5.1
只有电流出现问题，其他都正常。

**Comment by andrewleo** [comment]
在nexus5上测试了下，找了一个app跑了大概1个小时，结果没看到N/A的问题。
目前电流获取的逻辑是如果出现异常或者电流大小的绝对值超过500，则显示N/A,你可以试着改一下这个判断看看是否能正常显示，我们这边也确认下500这个阀值是否需要特殊处理

**Comment by dezng** [comment]
我nexus 5在之前用的时候装的应用比较多，测试wps，不断打开不同文件，电流值最高出现了1395，而且现在的快充就有通过提高充电电流来提升充电效率的，2000都可能会有

**Comment by andrewleo** [comment]
好的，感谢哈~ 我们有时间再测试下你说的场景，看下电流的情况。
感觉上可以不用做限制，直接拿通过读文件获取到的电流值
