### ISSUE TITLE
源代码的问题

### ISSUE THREAD

**Issue by chenxuan199206** [NetEase/Emmagee#55]
怎么设置了那个收集频率 收集的数量不对 我看了源代码是去读取logcat的(过滤)得到自己要的

**Comment by andrewleo** [comment]
配置好收集频率是定时收集的哈，和logcat没有关系。
目前需要根据logcat获取的是启动的时间，会尝试五次获取。不过在现在4.3以上的系统上，已经拿不到被测应用的启动时间了。
不知道你说的是不是这个问题？
