### ISSUE TITLE
怎么统计不了应用启动时间？

### ISSUE THREAD

**Issue by Surakey** [NetEase/Emmagee#57]
是必须root之后才能统计应用启动时间吗

**Comment by andrewleo** [comment]
我们的启动时间是通过解析logcat获取的，但是从Jelly Bean之后出于安全性考虑，只允许第三方应用获取一些系统日志，而不能获取其他应用的日志了，可以看我们的FAQ：https://github.com/NetEase/Emmagee/wiki/FAQ

```
Allows an application to read the low-level system log files. Not for use by third-party applications, because Log entries can contain the user's private information.
```

所以从4.3之后，除非root，否则是无法获取启动时间了。
