### ISSUE TITLE
测试显示的流量总是一两KB的往上涨，无法得到稳定的数据

### ISSUE THREAD

**Issue by fukuale** [NetEase/Emmagee#59]

**Comment by fukuale** [comment]
测试视频通话软件，保持通话20多分钟，但测得的总流量未超过400KB，是不是流量不准确啊

**Comment by andrewleo** [comment]
感谢反馈哈。
我们获取流量是通过getUidRxBytes，这个uid和应用是相关的哈，想问下你的视频通话软件，这个是否调用了另外的进程或者应用进行播放的？导致uid不同？

**Comment by msttyy** [comment]
@andrewleo 我也遇到这个问题，APP下载资源的流量没统计到
