### ISSUE TITLE
感觉流量测试不准确

### ISSUE THREAD

**Issue by assdftyui** [NetEase/Emmagee#60]
尝试用软件测试了网易云音乐下载两首歌的过程用了多少流量，加起来总共才800KB

**Comment by msttyy** [comment]
@assdftyui 我也遇到这个问题了，另外TrafficStats.getUidRxBytes(uid)、TrafficStats.getUidTxBytes(uid)计算的是应用所有接口数据，即使没有使用数据流量也会统计，说是内部通信产生的流量也会在内，所以多少会数据失真。

**Comment by xxxzhi** [comment]
我觉得是不是因为这个: http://stackoverflow.com/questions/17894966/getuidrxbytes-and-getuidtxbytes-always-return-0-in-android-4-3
