### ISSUE TITLE
流量监测不准确

### ISSUE THREAD

**Issue by mrx1203** [NetEase/Emmagee#61]
小米4 Android4.4.4，看视频一个小时流量也才消耗几MB，获取的uid为0，然后我改用ApplicationInfo来获取uid，就正常了。

![qq 20160713152957](https://cloud.githubusercontent.com/assets/20434332/16795223/ba38df48-490e-11e6-8787-8768042d7c23.png)

另外，csv文件有时候中文会显示乱码
![image](https://cloud.githubusercontent.com/assets/20434332/16795290/0b03645c-490f-11e6-8fd7-6f4387f72611.png)

**Comment by andrewleo** [comment]
感谢反馈。
流量不准确的问题您是换了android的api就可以了对吗？那可以给我们提个pull request，让更多人看到哈
