### ISSUE TITLE
魅族MX4手机上怎么不显示悬浮窗

### ISSUE THREAD

**Issue by EkinD** [NetEase/Emmagee#66]
魅族MX4手机上怎么不显示悬浮窗

**Comment by dezng** [comment]
国内 rom 基本都有权限设置，魅族的在 手机管家 -> 权限管理 -> 通知管理 中有针对应用悬浮窗的权限管理，你看是不是这里的设置问题。

**Comment by andrewleo** [comment]
是的。像小米，华为都有类似管家的软件，默认都会禁止悬浮窗，你可以确认下
之前遇到的都记在这里了：https://github.com/NetEase/Emmagee/wiki/Disappeared-floating-window%3F-See-here-to-make-it-show
