### ISSUE TITLE
内存不准确

### ISSUE THREAD

**Issue by islandone** [NetEase/Emmagee#69]
感谢开源这么好的工具
内存不准备啊 androidstudio 上面显示 30m 但是工具测出来的 90 这相差也太大了吧

**Comment by dezng** [comment]
VSS- Virtual Set Size 虚拟耗用内存（包含共享库占用的内存）
RSS- Resident Set Size 实际使用物理内存（包含共享库占用的内存）
PSS- Proportional Set Size 实际使用的物理内存（比例分配共享库占用的内存）
USS- Unique Set Size 进程独自占用的物理内存（不包含共享库占用的内存）
一般来说内存占用大小有如下规律：VSS >= RSS >= PSS >= USS

你可以先看看是不是和 studio 显示的不同类型的
查看命令是：procrank

**Comment by andrewleo** [comment]
感谢反馈哈。
Emmagee获取内存的方式如下，拿的是pss的值，会比应用实际的内存要高。

```
public int getPidMemorySize(int pid, Context context) {
		ActivityManager am = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
		int[] myMempid = new int[] { pid };
		Debug.MemoryInfo[] memoryInfo = am.getProcessMemoryInfo(myMempid);
		memoryInfo[0].getTotalSharedDirty();
		int memSize = memoryInfo[0].getTotalPss();
		return memSize;
	}
```

如果有需要的话，可以下载源代码进行修改哈。

**Comment by sk1kgn** [comment]
大佬你好，我在一个性能工具中，获取Android app内存值使用了和你提供的源码一样的方式，但对Sdk做了限制。
超过29的sdk再使用Debug.MemoryInfo的方式获取内存，数据和Adb dumpsys meminfo不一致，经排查，发现其实是更新频率非常低的问题，所以在sdk29以上的Android机，我使用了adb命令，但问题是 dumpsys meminfo很吃性能，会造成测试机的瞬时卡顿，影响fps的数值，（对比perfdog, 他们并不存在这一问题）
所以想请教一下大佬，关于这一块，有没有比较好的解决方案。望回复，感谢！
（给您发了邮件，可能的话直接popo上沟通吧shenke02@corp.netease.com）
