### ISSUE TITLE
栈顶Activity名称是com.netease.qa.emmagee/com.netease.qa.emmagee.activity.MainPageActivity

### ISSUE THREAD

**Issue by liyuanhong** [NetEase/Emmagee#70]
你好，请问栈顶Activity名称是com.netease.qa.emmagee/com.netease.qa.emmagee.activity.MainPageActivity而不是我要测试应用的Activity呢。

**Comment by andrewleo** [comment]
感谢反馈。请问是不是在5.0以上的手机上出现这个问题的？
原因是在android 5.0.1版本以上，google出于安全性考虑，不允许第三方应用获取当前运行的进程了，详细请看这个issue哈： #49
