### ISSUE TITLE
Nexus 5x机型获取不到应用占CPU率

### ISSUE THREAD

**Issue by weppeng** [NetEase/Emmagee#72]
Nexus 5x (android 7.1)
输出的应用占用CPU率一直为0；
输出：FileNotFoundException: /proc/0/stat: open failed: ENOENT (No such file or directory)
PID不对，就去试着调试将真的PID替换，替换之后仍报FileNotFoundException这个错误
难道是Emmagee不支持该机型获取应用CPU占用率吗？
急，求解释一下

**Comment by andrewleo** [comment]
感谢反馈哈！
您的意思是通过emmagee获取到的pid是0，但是您将pid修改为正确值后，emmagee仍然报找不到文件？
应用启动后是否通过adb shell查看过该文件存在与否？

**Comment by andrewleo** [comment]
我这边在`谷歌 PIXEL（7.1）`测试了下，发现：
（1）7.X上无法通过top获取到其他应用的pid了，应该是google提高安全性的又一举措
（2）如果拿到正确的pid，是可以通过读取/proc/pid/stat获取到cpu信息的；您可能拿到的pid有错误，应用每次重新启动，pid都会改变。
如果您比较着急，可以先通过给定正确的pid临时解决问题。7.X的系统近期我们会适配下，看看是否有其他的解决方案，之后会发布新版本予以支持~

**Comment by weppeng** [comment]
首先非常感谢@andrewleo的回复，的确，7.x获取不到pid,每次重启应用pid会变这也清楚，不过，就算用正确的pid,用/proc/pid/stat获取不到cpu信息。再个，用adb shell命令查不到文件。这就比较尴尬了。。。

**Comment by andrewleo** [comment]
是的，apk是没有权限访问该文件的，不过通过adb shell可以查看到：![image](https://cloud.githubusercontent.com/assets/3241895/23537398/ce4c2ac6-0006-11e7-80d9-ad3e5fd3c352.png)

初步参考了下面两个帖子，可以基本下结论：7.X开始部分之前能获取的信息已经开始被禁止了
1. news about Nougat：http://www.androidauthority.com/android-7-0-features-673002/
    该帖子提到7.0开始对文件的权限进行的限制，但是没有提到限制了哪些文件
2. restrictive file system in Nougat：https://code.google.com/p/android/issues/detail?id=205565
这个帖子里大家讨论最多的也就是文件访问权限的问题，导致很多app在7.0上就无法支持了；google的这一举措也是为了安全性考虑，甚至也把blackberry以及iOS的权限控制搬了出来。
