### ISSUE TITLE
actionbar_bg.9.png

### ISSUE THREAD

**Issue by luoxiaoji** [NetEase/Emmagee#77]
这个文件名错了吧，会编译不过去。

**Comment by andrewleo** [comment]
这个是android中的“点九”文件哈，是一种特殊的图片形式，扩展名就是.9.png哈。
https://isux.tencent.com/android-ui-9-png.html

**Comment by luoxiaoji** [comment]
不好意思，是我文盲了，但是导入 android studio 中的确会报这个错，好像是找不到什么东西。
我把.9去掉了就不报错了

**Comment by andrewleo** [comment]
as对 .9 文件的要求貌似严格些，所以会出现编译问题，你可以看下这个文章，看看是否有帮助：http://codecloud.net/15026.html

**Comment by luoxiaoji** [comment]
好的，十分感谢，不过我把.9去掉编译也能过，或许不会影响什么？

**Comment by andrewleo** [comment]
如果没有什么问题最好，你可以打包看下是否正常。我们还没有试过将emmagee从eclipse转到as上。

**Comment by luoxiaoji** [comment]
试过，除了.9无法编译过之外，能打包。

**Comment by andrewleo** [comment]
那就需要修改点9图片，补全点9图的四边黑线了。可以尝试：`用draw9Patch工具，打开.9图补全黑线`
