### ISSUE TITLE
华为 honor使用Emmagee遇到的问题：

### ISSUE THREAD

**Issue by xu-xiaojing** [NetEase/Emmagee#81]
1.统计的数据电流为N/A；
2.即使手机root后仍然获取不到开机启动时间；
3.配置邮件信息后，进行应用测试，点击停止，Emmagee崩溃

**Comment by xu-xiaojing** [comment]
Android版本：4.4.2

**Comment by andrewleo** [comment]
首先确认下您是否用的最新的2.4.1版本哈？如果是的话，
1、电流为N/A，应该是还没有适配这款机器，可以把具体型号贴出来哈。
2、手机已经root，但emmagee需要申请到root权限才能拿到日志，继而统计到启动时间，但当前并没有申请root权限的功能，因此还是拿不到。下个版本加入这块功能
3、应用测试期间，浮窗上的数据都能正常获取？只是在主动停止测试后，emmagee就崩溃退出了是吗？

**Comment by xu-xiaojing** [comment]
是最新的2.4.1版本呢
1.型号：CHM-TL00H
3.浮窗上的数据只有电流没法获取，对，手动点击停止测试后，emmagee就崩溃了，提示：异常退出

**Comment by xu-xiaojing** [comment]
而且我在手机上允许给Emmagee授Root权限了

**Comment by andrewleo** [comment]
1. 允许给emmagee授权的意思是：你在手机管家中开启了允许申请权限？但emmagee并没有主动申请，所以在执行logcat时不会用su权限去拿日志哈。
1. 电流是需要跟着机型适配的，而且不保证厂商会将电流记录在文件中，我们只能试试看能否找到。

**Comment by xu-xiaojing** [comment]
哦，好的，THX~

**Comment by andrewleo** [comment]
手动停止测试后，emmagee崩溃
- 这个你方便通过adb logcat拿到具体日志吗？我这边找到同样的机型和系统，正确的邮件配置，错误的密码/smtp等，都试了下，没有出现crash的问题。

**Comment by andrewleo** [comment]
目前进入power_supply目录查找以及工程模式后，都也没有找到电流的数据。看来应该是没有办法支持这款机型了。
