### ISSUE TITLE
小米MI MAX使用Emmagee无法统计到流量

### ISSUE THREAD

**Issue by LYCBD1** [NetEase/Emmagee#83]
在小米MI MAX上使用Emmagee统计到的流量值恒为0，其余统计项正常

**Comment by andrewleo** [comment]
我试了下6.0.1版本的MI MAX，测试了UC浏览器和云阅读，均可以获取到流量哈，麻烦您确认下：
1、手机是否没有网络连接？这样流量确实会为0kb，如果开启后再观察看看？
2、如果有网络连接，还是获取不到流量，能否把Emmagee的日志贴一下？

**Comment by LYCBD1** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>邮件正文>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
致阅者：
      你看看你要的是不是这个，不是的话，你教我一下，我给你找你需要的东西
      我试过测萤石视频观看30分钟的记录，但流量也都是为0
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
黄宇浩
邮箱：huangyuhao@antelope.cloud
所属：测试部
公司：深圳羚羊视频云科技有限公司
官网：www.topvdn.com
地址：深圳市南山区高新科技园后海大道2388号怡化金融科技大厦1301室
+++++++++++++++++++++++++++++++END+++++++++++++++++++++++++++++++
 
发件人： Liu Xiao
发送时间： 2017-04-20 10:41
收件人： NetEase/Emmagee
抄送： LYCBD1; Author
主题： Re: [NetEase/Emmagee] 小米MI MAX使用Emmagee无法统计到流量 (#83)
我试了下6.0.1版本的MI MAX，测试了UC浏览器和云阅读，均可以获取到流量哈，麻烦您确认下：
1、手机是否没有网络连接？这样流量确实会为0kb，如果开启后再观察看看？
2、如果有网络连接，还是获取不到流量，能否把Emmagee的日志贴一下？

**Comment by andrewleo** [comment]
您是有挂载日志或者截图等附件吗？回复中并没有看到哈。
日志的获取您可以这样操作下：
* adb logcat -c 清理下日志
* adb logcat > output.file 开始写入日志到文件中
* emmagee启动被测应用，开始测试
* 等悬浮窗以及里面的数据出现后，大约等待个10s，将adb logcat > output.file命令终止
* 将output.file文件上传或者是内容放到[GIST](https://gist.github.com)上，然后把链接贴到这个issue中哈。

**Comment by LYCBD1** [comment]
邮件中是有现象的附件的，但是回的邮件在评论里没看到，不好意思
我按你的方法抓到日志了，但是上传不上来，不明白为什么，可以直接发你邮箱吗？

**Comment by andrewleo** [comment]
那可以放到gist上哈。https://gist.github.com/ 你可以把日志贴到这里，然后链接挂一下就可以
如果这个也不行，那直接邮件我吧

**Comment by LYCBD1** [comment]
https://gist.github.com/LYCBD1/88d678836fd04d36877ddd929bd2180d.js

**Comment by LYCBD1** [comment]
你看看行不行，不行的话我再弄

**Comment by andrewleo** [comment]
https://gist.githubusercontent.com/LYCBD1/88d678836fd04d36877ddd929bd2180d/raw/f76ca9a2c4635447fba1bf8b2f14fe9be5710ccc/gistfile1.txt 日志是这个吧？

**Comment by LYCBD1** [comment]
对，没错，为什么我们的链接差距这么大

**Comment by andrewleo** [comment]
系统是什么版本的？测试任何应用都是没有流量吗？

**Comment by LYCBD1** [comment]
系统为MIUI 8.2(8.2.2.0 MBCCNDL)，Android 6.0.1 MMB29M
目前共测试了7款app都没有流量，分别为小鱼在家、360摄像机、萤石云视频、爱耳目摄像机、小蚁摄像机、微信以及UC浏览器

**Comment by andrewleo** [comment]
查看了文档，_Nougat_以后以后就无法通过TrafficStats获取流量了。
```
Starting in N this will only report traffic statistics for the calling UID. It will return UNSUPPORTED for all other UIDs for privacy reasons. To access historical network statistics belonging to other UIDs, use NetworkStatsManager.
```
但小米的8.2系统确实有些奇怪，是基于6.0.1进行的修改，也获取到正确的uid了，但看了下/proc下面没有uid_stat目录，通过getUidTxBytes获取的流量为0，感觉应该是系统对这个API做了什么手脚。我们再看看有没有其他什么办法。

**Comment by LYCBD1** [comment]
真是麻烦了，万分感谢
我主要不明白的差异是为什么同样都是小米MI MAX的手机你们的正常，我们这边拿不到数据
那个目录之所以没有，会不会是因为没有权限去创建那个目录

**Comment by andrewleo** [comment]
我这边正常是因为不是MIUI 8.2的系统哈。版本不一样，小米的系统升级后应该改了流量那块

**Comment by LYCBD1** [comment]
哦~，好的，如果还有什么需要帮忙的就说，虽然不是很懂技术，但我会尽力配合，顺便学习一下
还有就是希望你们这款APP今后能有iOS上的版本，不然为了统计iOS上的数据还要专门去买台Mac，有点奢侈

**Comment by andrewleo** [comment]
恩，也感谢你反馈的问题，帮我们继续改善。
如果有兴趣可以尝试给Emmagee贡献代码~

**Comment by LYCBD1** [comment]
我google了一下找不到对应文件夹的问题，你看看这个网址里写的对你们有用没https://testerhome.com/topics/2068
因为我根据里面所提示的路径，在MIUI8.2上找到了对应的东西

**Comment by andrewleo** [comment]
恩，这个我们之前有尝试过，由于apk没有读文件权限放弃了。
既然你试过可以读取到，我们今天再验证看下是否可以读到以及数据的准确性，十分感谢~

**Comment by LYCBD1** [comment]
我是adb pull那样用命令行拿出文件的，不是
![tim 20170424114308](https://cloud.githubusercontent.com/assets/27794673/25323252/a1870836-28f0-11e7-9221-c63572eb7936.png)

**Comment by LYCBD1** [comment]
不是用apk

**Comment by andrewleo** [comment]
/proc/net/xt_qtaguid/stats 通过adb shell cat是可以读取的，里面的流量数据也存在。但是十分抱歉，我们这台MAX手机，apk是无法读到该文件里面的内容的，应该是权限问题。
看了6.0.1的源码，getUidRxBy也是读取的xt_qtaguid文件。
```
https://android.googlesource.com/platform/frameworks/base/+/android-6.0.1_r72/core/jni/android_net_TrafficStats.cpp
```

**Comment by LYCBD1** [comment]
你可以改完这个路径后发我apk吗？
因为我这边没有Android的编译环境，所以没法修改代码后再进行编译
而且我也不是开发人员，不是很明白怎么操作
huangyuhao@antelope.cloud是我的邮箱，如果可以的话就发我吧

**Comment by andrewleo** [comment]
无法解决
