### ISSUE TITLE
last release carries wrong version

### ISSUE THREAD

**Issue by IzzySoft** [NetEase/Emmagee#87]
Just a note: Please don't forget to increase `versionCode` and `versionName` when creating a new APK:

    com.netease.qa.emmagee_2.4.1.apk
    package: name='com.netease.qa.emmagee' versionCode='32' versionName='2.4.1' platformBuildVersionName='4.0.4-1406430'
    com.netease.qa.emmagee_2.5.apk
    package: name='com.netease.qa.emmagee' versionCode='32' versionName='2.4.1' platformBuildVersionName='4.4.2-1456859'

So currently, v2.5 identifies itself as 2.4.1.

**Comment by andrewleo** [comment]
Much thanks for you reminding！
I will correct `versionCode` and `versionName` right now.

**Comment by andrewleo** [comment]
Fixed！

**Comment by IzzySoft** [comment]
Confirmed – thanks!
