### ISSUE TITLE
报表中帧率都显示-1

### ISSUE THREAD

**Issue by 31515964** [NetEase/Emmagee#92]
手机：三星 Galaxy J7 Prime
型号：SM-G6100
系统：6.0.1
未root
安装：Emmagee2.5版本

问题：尝试过多款软件，报表中的帧率都显示为-1，帧率怎么都获取失败，请问需要怎么处理？

**Comment by andrewleo** [comment]
帧率需要root才可以获取啊，未root的手机显示为-1

**Comment by binsalem** [comment]
thanks
