### ISSUE TITLE
请问一下,这个获取内存的原理是什么? 

### ISSUE THREAD

**Issue by RealLau** [NetEase/Emmagee#93]
你好, 很想知道一下原理, 是如何获取到的内存数据?
跟adb shell dumpsys meminfo获取内存的数据一致还是跟adb shell top命令获取到的数据一致?

**Comment by andrewleo** [comment]
目前Emmagee是获取的PSS，也就是包含部分共享内存的数据，比实际占用的物理内存要高一些的。

------------
dumpsys meminfo:
![image](https://user-images.githubusercontent.com/3241895/29357090-ea24d606-82a8-11e7-89f5-88a095ab2522.png)

top里面的是vss和rss，和Emmagee获取的不一样：
![image](https://user-images.githubusercontent.com/3241895/29357153-22728e22-82a9-11e7-8101-d593215fa672.png)

**Comment by RealLau** [comment]
好的 谢谢了哈

**Comment by RealLau** [comment]
好的 谢谢了哈
