### ISSUE TITLE
悬浮窗无法显示

### ISSUE THREAD

**Issue by qianchen1111** [NetEase/Emmagee#94]
## Environment
机型：360N4S
* Emmagee version
2.5.1版本
* Device Information: **Brand**, **Model**, **System**.

## Link to Emmagee logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Emmagee logs, and link them here. 
Do _NOT_ paste your full Emmagee logs here, as it will make this issue very long and hard to read!

**Comment by andrewleo** [comment]
感谢反馈哈。
最好把您的设备型号，系统版本贴出来，如果有log就更好了。否则比较难定位问题 :)

**Comment by qianchen1111** [comment]
除了无法显示悬浮窗，流量也为0
手机360N4S
型号：1505-A01
处理器：helio X20十核处理器
Android版本：6.0
内核版本：3.18.22+
版本号：V109

**Comment by andrewleo** [comment]
#### 悬浮窗未显示问题（已解决）
* 原因是国内大部分厂商都加入权限管理，悬浮窗的权限默认是关闭的，需要手动设置开启。
解决方法已经更新到wiki上了，可以访问这里查看：[开启360悬浮窗权限](https://github.com/NetEase/Emmagee/wiki/Disappeared-floating-window%3F-See-here-to-make-it-show#360)

#### 流量显示为0
* 我试了下两个App，有网络请求的情况下，流量均有增长，目前未发现流量为0的问题
想问下您测试的App是否有网络请求？如果换个App测试流量还是为0吗？
<img src="https://user-images.githubusercontent.com/3241895/29545414-cb1b9a20-8720-11e7-8e78-ac75ae86de55.png" width="200">

**Comment by qianchen1111** [comment]
我用了4g移动网络访问了QQ浏览器，但是流量和电流都显示为0
![_20170822101152](https://user-images.githubusercontent.com/31162015/29545746-a18adf16-8722-11e7-827a-b90fdf755ca2.jpg)

**Comment by andrewleo** [comment]
试了下qq浏览器，在wifi的情况下是可以有流量的。电流是因为不同手机的电流文件不一样，需要适配，我们暂时还没有做
<image src="https://user-images.githubusercontent.com/3241895/29546027-6a8c52ae-8724-11e7-9f58-86a86dcd8524.png" width="200">

由于我们手头暂时没有sim卡可以试验，建议：
* 您看看能不能在wifi的情况下再试试看？
* 试试其他的App，看看是不是所有的App都拿不到流量

我看看能不能找到SIM卡再测试下。

**Comment by qianchen1111** [comment]
我用了WiFi，换了手机淘宝，流量还是为0
![2](https://user-images.githubusercontent.com/31162015/29548800-4b1a26d2-8736-11e7-8044-51639c726101.jpg)

**Comment by andrewleo** [comment]
您确定使用的是2.5版本对吧？因为我这边有一台和您完全一样的设备，电流流量都可以获取。
如果确实是，麻烦您把手机日志作为附件上传下。如果不清楚怎么获取可以按如下步骤操作（确保本地有adb）：
1、adb logcat -c 清理日志
2、adb logcat -v time > logcat 将日志保持到pc端
3、启动任意应用的测试，可以等个十几秒，如果流量和电流一直是0就可以把步骤2的命令停止了
4、上传附件到这个issue下面

**Comment by wednesday410** [comment]
1、2.5版本，红米note4x（Android6.0.1），流量一直为0，其他都可正常显示；
2、2.5版本，oppo A57（Android5.1），电量一直为0，其他都可正常显示；

**Comment by andrewleo** [comment]
#### oppo A57（Android5.1）电流为0
* 这款手机看了下，电池相关的仍然在这个目录下 _/sys/class/power_supply/battery_ ，里面也有current_now但数值为0，其他的文件看了下也不像电流数据，所以个人觉得可能驱动并没有将电流信息记录在系统文件中

#### 红米note4x（Android6.0.1）流量为0
* 已经确认这款机器通过官方的流量统计类TrafficStats 获取到的数据为0，但实际上流量文件是有数据的，原因不明。
* 我们最迟明天会修改该问题，请关注2.5.1

**Comment by andrewleo** [comment]
可以试下2.5.1版本有没有解决你的问题。
下载地址：https://github.com/NetEase/Emmagee/releases

**Comment by qianchen1111** [comment]
问题已解决，谢谢！
