### ISSUE TITLE
无法支持7.0及以上版本

### ISSUE THREAD

**Issue by xuxiao101004** [NetEase/Emmagee#97]
## The problem

Describe the issue you are experiencing, or features you want. 

## Environment

* Emmagee version
* Device Information: **Brand**, **Model**, **System**.

## Link to Emmagee logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Emmagee logs, and link them here. 
Do _NOT_ paste your full Emmagee logs here, as it will make this issue very long and hard to read!

**Comment by andrewleo** [comment]
由于google对权限的收紧，目前Emmagee的实现方式已经不支持7.0以上的机型了
![image](https://user-images.githubusercontent.com/3241895/32527625-f0c6bf4e-c469-11e7-93ca-b8b96bf6ad44.png)
详细可以参考这个issue：https://github.com/NetEase/Emmagee/issues/72 下的讨论
